# 选项及全局变量定义与初始化 根CMakeLists.txt执行一次

set(EMSCRIPTEN FALSE)
set(LINUX FALSE)
set(WINDOW FALSE)
set(CONSOLE FALSE)

message("CMAKE_SYSTEM_NAME:" ${CMAKE_SYSTEM_NAME})
if ("${CMAKE_SYSTEM_NAME}" STREQUAL "Emscripten")
    set(EMSCRIPTEN TRUE)
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    set(LINUX TRUE)
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
    set(WINDOW TRUE)
else()
    set(CONSOLE TRUE)
endif()

# 编译类型确定
string(TOUPPER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_UPPER)
if ("${CMAKE_BUILD_TYPE_UPPER}" STREQUAL "RELEASE")
    set(CMAKE_BUILD_TYPE Release)
    set(DEBUG FALSE)
    message("==================RELEASE===================")
else()
    set(CMAKE_BUILD_TYPE Debug)
    set(DEBUG TRUE)
    message("==================DEBUG===================")
endif()

# 源码源
if (NOT DEFINED USE_GITHUB_SOURCE)
    set(USE_GITHUB_SOURCE FALSE)
endif()

# 第三方库源码目录
if (USE_GITHUB_SOURCE) 
    set(EXTERNAL_LIB_SOURCE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/github)
else()
    set(EXTERNAL_LIB_SOURCE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/gitlab)
endif()
# 内部第三方库
set(INTERNAL_LIB_SOURCE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/source)
# 第三方库CMake目录
set(EXTERNAL_LIB_CMAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/cmake/3dparty)
# 第三方库安装根目录
set(EXTERNAL_LIB_INSTALL_ROOT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/prebuilt/${CMAKE_SYSTEM_NAME})
# 第三方编译类型
set(EXTERNAL_LIB_BUILD_TYPE ${CMAKE_BUILD_TYPE})
# 第三方库安装目录
set(EXTERNAL_LIB_INSTALL_DIRECTORY ${EXTERNAL_LIB_INSTALL_ROOT_DIRECTORY}/${EXTERNAL_LIB_BUILD_TYPE})
# 第三方库编译目录
set(EXTERNAL_LIB_BUILD_DIRECTORY ${EXTERNAL_LIB_INSTALL_ROOT_DIRECTORY}/Build/${EXTERNAL_LIB_BUILD_TYPE})

message("EXTERNAL_LIB_SOURCE_DIRECTORY=" ${EXTERNAL_LIB_SOURCE_DIRECTORY})
message("EXTERNAL_LIB_INSTALL_DIRECTORY=" ${EXTERNAL_LIB_INSTALL_DIRECTORY})
message("EXTERNAL_LIB_BUILD_DIRECTORY=" ${EXTERNAL_LIB_BUILD_DIRECTORY})
message("EXTERNAL_LIB_CMAKE_DIRECTORY=" ${EXTERNAL_LIB_CMAKE_DIRECTORY})
message("EXTERNAL_LIB_BUILD_TYPE=" ${EXTERNAL_LIB_BUILD_TYPE})

# 第三方库变量属性定义
define_property(GLOBAL PROPERTY EXTERNAL_INCLUDE_LIST_PROPERTY BRIEF_DOCS "第三方库头文件目录列表" FULL_DOCS "第三方库头文件目录列表")
define_property(GLOBAL PROPERTY EXTERNAL_LIB_LIST_PROPERTY BRIEF_DOCS "第三方库库路径列表" FULL_DOCS "第三方库库路径列表")
define_property(GLOBAL PROPERTY EXTERNAL_MACRO_DEFINE_LIST_PROPERTY BRIEF_DOCS "external macro define list" FULL_DOCS "external macro define list")

# 库路径前缀后缀设定
if (MSVC)
    set(STATIC_LIB_PREFIX "")
    set(STATIC_LIB_SUFFIX ".lib")
else()
    set(STATIC_LIB_PREFIX "lib")
    set(STATIC_LIB_SUFFIX ".a")
endif()
