set(LIB_NAME "Assimp")
set(${LIB_NAME}_DIRNAME "assimp")
# set(${LIB_NAME}_DIRNAME "assimp-5.0.1")
list(APPEND ${LIB_NAME}_CONFIG "-DBUILD_SHARED_LIBS=OFF")
if (MSVC)
    list(APPEND ${LIB_NAME}_CONFIG "-DUSE_STATIC_CRT=OFF")
endif()
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_GLTF_IMPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_FBX_IMPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_COLLADA_IMPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_GLTF_EXPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_FBX_EXPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_COLLADA_EXPORTER=ON")
list(APPEND ${LIB_NAME}_CONFIG "-DASSIMP_BUILD_TESTS=OFF")

if (EMSCRIPTEN)
    set(${LIB_NAME}_INTERFACE_LIBRARY_NAME "assimpd")
else()
    if (MSVC)
        if (DEBUG)
            list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY ${EXTERNAL_LIB_INSTALL_DIRECTORY}/${${LIB_NAME}_DIRNAME}/lib/assimp-vc143-mtd.lib)
            list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY ${EXTERNAL_LIB_INSTALL_DIRECTORY}/${${LIB_NAME}_DIRNAME}/lib/zlibstaticd.lib)
        else()
            list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY ${EXTERNAL_LIB_INSTALL_DIRECTORY}/${${LIB_NAME}_DIRNAME}/lib/assimp-vc143-mt.lib)
            list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY ${EXTERNAL_LIB_INSTALL_DIRECTORY}/${${LIB_NAME}_DIRNAME}/lib/zlibstatic.lib)
        endif()
    endif()
endif()

# 5.0.1
# list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY "D:/workspace/cmake-test/prebuilt/Windows/Debug/assimp-5.0.1/lib/assimp-vc143-mtd.lib")
# list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY "D:/workspace/cmake-test/prebuilt/Windows/Debug/assimp-5.0.1/lib/IrrXMLd.lib")
# list(APPEND ${LIB_NAME}_INTERFACE_LIBRARY "D:/workspace/cmake-test/prebuilt/Windows/Debug/assimp-5.0.1/lib/zlibstaticd.lib")
build_external_lib(${LIB_NAME})

# 5.2.5 fbx 旋转存在问题 5.0.1 可用