set(LIB_NAME "glad")
set(${LIB_NAME}_DIRNAME "glad")
set(${LIB_NAME}_CMAKE_DIR ${INTERNAL_LIB_SOURCE_DIRECTORY}/glad) 
set(${LIB_NAME}_INTERFACE_LIBRARY_NAME "glad_gles2")
build_external_lib(${LIB_NAME})

# add_subdirectory(${PROJECT_ROOT_DIRECTORY}/external/glad glad)
# if (USE_GLAD_GLES2)
#     target_link_libraries(window3d PUBLIC LuaGui glad_gles2)
#     target_compile_definitions(window3d PUBLIC USE_GLAD_GLES2)
# else()
#     target_link_libraries(window3d PUBLIC LuaGui glad_gl)
#     target_compile_definitions(window3d PUBLIC USE_GLAD_GL)
# endif()

# set(GLAD_SOURCE_DIR ${PROJECT_ROOT_DIRECTORY}/external/glad)
# add_library(glad_gl STATIC src/gl.c)
# target_include_directories(glad_gl PUBLIC ${GLAD_SOURCE_DIR}/include)
# add_library(glad_gles2 STATIC src/gles2.c)
# target_include_directories(glad_gles2 PUBLIC ${GLAD_SOURCE_DIR}/include)