
set(LIB_NAME "Lua")
set(${LIB_NAME}_DIRNAME "lua")
set(${LIB_NAME}_CMAKE_DIR "${EXTERNAL_LIB_CMAKE_DIRECTORY}/${${LIB_NAME}_DIRNAME}")
set(${LIB_NAME}_SOURCE_DIR "${EXTERNAL_LIB_SOURCE_DIRECTORY}/${${LIB_NAME}_DIRNAME}")
set(${LIB_NAME}_CONFIG "-DSOURCE_CODE_DIR=${${LIB_NAME}_SOURCE_DIR}")
set(${LIB_NAME}_INTERFACE_INCLUDE_DIR "${EXTERNAL_LIB_SOURCE_DIRECTORY}/LuaBridge-2.6/Source")

build_external_lib(${LIB_NAME})
