set(LIB_NAME "SDL2_net")
set(${LIB_NAME}_DIRNAME "SDL2_net-2.2.0")
list(APPEND ${LIB_NAME}_CONFIG "-DBUILD_SHARED_LIBS=OFF")
list(APPEND ${LIB_NAME}_CONFIG "-DSDL2_INCLUDE_DIR=${SDL2_INSTALL_DIRECTORY}/include/SDL2")
list(APPEND ${LIB_NAME}_CONFIG "-DSDL2_LIBRARY=${SDL2_INSTALL_DIRECTORY}/lib")
set(${LIB_NAME}_INTERFACE_LIBRARY_NAME "SDL2_net-staticd")
build_external_lib(${LIB_NAME})

